### ISSUE TITLE
[FR] Multiple account selection

### ISSUE THREAD

**Issue by randompea** [lo-cafe/winston#283] opened 2023-11-21 22:03 UTC
**Is your feature request related to a problem? Please describe.**
When I hold down on my user and it says multi account coming soon
**Describe the solution you'd like**
I want it now
**Describe alternatives you've considered**
Using the reddit app
**Additional context**

**Comment by ojsef39** [comment] 2023-11-22 14:17
Duplicate of issue #39

**Closed by ojsef39** 2023-11-22 14:17 UTC
Labels: feature/enhancement
