### ISSUE TITLE
[FR] Share as image (comment or post)

### ISSUE THREAD

**Issue by jsaltzman** [lo-cafe/winston#471] opened 2024-03-23 16:10 UTC
When I text links to comments or posts on iMessage, it's tough for a recipient to understand what it is at a glance

**Describe the solution you'd like**
When I select share I'd like to share a screenshot of the comment or post, similar to how Apollo handled this.

**Describe alternatives you've considered**
M/A

**Additional context**
N/A

**Comment by ojsef39** [comment] 2024-03-23 16:14
Hi, thanks for your feature request! I’m closing this because it’s a duplicate of [https://github.com/lo-cafe/winston/issues/161](https://github.com/lo-cafe/winston/issues/161)

**Closed** 2024-03-23 16:14 UTC
Labels: feature/enhancement
