### ISSUE TITLE
[CRASH] Crash on opening on v 1.0.0 (161) on iOS 16

### ISSUE THREAD

**Issue by Colindm8** [lo-cafe/winston#227] opened 2023-11-10 22:09 UTC
**Describe the bug**
App crashes on launch on my devices running iOS 16

**To Reproduce**
Open app
App immediately crashes back to Home Screen

**Expected behavior**
App opens

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Winston (please complete the following information):**
 - Version 1.0.0
 - Build Number 161

**Device (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.6.1

 - Device: iPad Pro (11-inch) (3rd generation)
 - OS: iOS 16.5

 - Device: iPad Mini (6th generation)
 - OS: iOS 16.6

**Additional context**

**Comment by Colindm8** [comment] 2023-11-10 22:12
https://github.com/lo-cafe/winston/assets/150486800/fb0fc208-107f-4057-b25d-334cfbc1ddfb

Video of crash uploaded.

**Comment by ojsef39** [comment] 2023-11-11 00:49
duplicate of #212

**Closed** 2023-11-11 00:49 UTC
Labels: bug/fix, bug=causes crash
