### ISSUE TITLE
[BUG] Issue with Comment Box Refresh and Duplicating Text During Reply

### ISSUE THREAD

**Issue by cptjpk** [lo-cafe/winston#329] opened 2023-12-07 15:56 UTC
**Describe the bug**

While replying to comments, I’ve encountered a recurring issue where the comment box refreshes unexpectedly. This causes the text I’m typing to duplicate itself in the middle of the existing text. This disrupts the flow of writing and leads to confusion.

**To Reproduce**
1. Swipe to reply
2. Insert text and it will happen

**Expected behavior**
The comment box should remain stable without any refresh or duplication of text, allowing for a smooth and uninterrupted typing experience.

**Screenshots**
https://github.com/lo-cafe/winston/assets/77907794/9a738ec8-b1b3-4ea4-894b-3f5f39fb4907

**Winston (please complete the following information):**
 - Version Beta v1.1.0
 - Build Number 228

**Device (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: ios 17.2 RC1

**Additional context**
N/A

**Comment by ojsef39** [comment] 2023-12-29 19:36
hey , thanks for your feedback, but this is a duplicate of #108 so im going to close this issue :)

**Closed by ojsef39** 2023-12-29 19:36 UTC
Labels: bug/fix
