### ISSUE TITLE
[BUG] random users assigned to comments

### ISSUE THREAD

**Issue by dvandersluis** [lo-cafe/winston#200] opened 2023-10-14 22:31 UTC
**Describe the bug**
When Winston loads more comments, the usernames given to each comment do not match the actual users shown on Reddit. 

**To Reproduce**
1. Open a thread in Winston
2. Click on a load more comments button
3. Comments loaded will not have the correct usernames when compared with Reddit. 

**Expected behavior**
Loaded comments should be attributed to the correct users. 

**Screenshots**
Winston:
![image](https://github.com/lo-cafe/winston/assets/57964/f70911fd-0a8d-4120-b46b-5c45e9700a8b)

Reddit:
![image](https://github.com/lo-cafe/winston/assets/57964/c22f8972-1e30-4c9f-8b7d-02771b848416)

**Winston (please complete the following information):**
 - Version Beta v1.0
 - Build Number 144

**Device (please complete the following information):**
 - iPhone 15 Pro
 - OS: ios 17.0.3

**Additional context**
The same thing happened on an iPhone 13 Pro on iOS 16.

**Comment by ojsef39** [comment] 2023-10-15 15:52
duplicate of #92, closing this

**Closed** 2023-10-15 15:52 UTC
Labels: bug/fix, duplicate
