### ISSUE TITLE
[BUG] [ALPHA] Saved Posts View’s Loading Screen Does Not Respect Theme

### ISSUE THREAD

**Issue by Psyclaire** [lo-cafe/winston#435] opened 2024-02-02 19:29 UTC
**Describe the bug**
Saved post view only applies theme colors once the contents of the page are loaded/displayed. The Saved post feed background is black until the content is displayed, and only then will the theme be applied to the view.

**To Reproduce**
1. Go to saved posts
2. Observe the ignored UI colors
3. Allow the page to load
4. *Then* the theme will be applied

**Expected behavior**
The theme should be applied prior to the loaded contents within the saved post tab.

**Winston (please complete the following information):**
 - Version [Alpha 341]

**Device (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.3

**Comment by ojsef39** [comment] 2024-02-20 17:19
@Psyclaire can i close this? seems for me at least like the issue is gone :)

**Comment by Psyclaire** [comment] 2024-02-20 17:39
> @Psyclaire can i close this? seems for me at least like the issue is gone :)

Yes, this was resolved recently. It is good to close👍

**Closed** 2024-02-20 18:45 UTC
Labels: bug/fix
