### ISSUE TITLE
[BUG] videos only have sound with silent mode disabled

### ISSUE THREAD

**Issue by makiele** [lo-cafe/winston#503] opened 2024-06-24 01:03 UTC
**Describe the bug**
after updating to 1.1.5, the sound of videos only seems to work while the iPhones silent mode is disabled. when silent mode is enabled, videos don't output any sound. does not matter if you push the volume buttons or use the volume icon in the upper right hand corner.

**To Reproduce**
1. enable silent mode
2. open a post with a video
3. play said video
4. try to increase or lower the volume
5. no sound is output

**Expected behavior**
if a video is manually unmuted by increasing the volume videos should ouput sound even if in silent mode.

**Winston (please complete the following information):**
 - Version [e.g. Beta v1.1.5]
 - Build Number [e.g. 392]

**Device (please complete the following information):**
 - Device: [e.g. iPhone 15 Pro]
 - OS: [e.g. iOS 17.5.1]

**Additional context**
tried to disable the options "default mute fullscreen videos" and "automatically play videos (muted)" unter settings > behavior - but that didn't help either.

**Comment by ojsef39** [comment] 2024-06-24 10:29
duplicate of [https://github.com/lo-cafe/winston/issues/394](https://github.com/lo-cafe/winston/issues/394)

**Closed** 2024-06-24 10:29 UTC
Labels: bug/fix
