### ISSUE TITLE
Cant see links on posts

### ISSUE THREAD

**Issue by ojsef39** [lo-cafe/winston#123] opened 2023-10-09 10:13 UTC
Hi! 
I’m having a problems with links, can’t see them, can’t click them. Check out screenshots.
Using latest version of Winston (139), iPhone 14 Pro, iOS 17.0.2
I’ve tried to reinstall, use another theme, but to no success.

![image](https://github.com/lo-cafe/winston/assets/43563019/55ccb1a2-44dc-4e61-ae74-b7fbb8bd6524)
![image](https://github.com/lo-cafe/winston/assets/43563019/c2c7e5c5-7c50-48c2-a8e5-9a68fc886831)

——————
Related to #63 
https://discord.com/channels/1094807340903039048/1158374457535115294

**Comment by Frostplexx** [comment] 2023-11-25 17:19
Duplicate of #63

**Closed by Frostplexx** 2023-11-25 17:19 UTC
Labels: bug/fix, severity/priority=medium
