### ISSUE TITLE
[FR] Add downloading videos directly through the app

### ISSUE THREAD

**Issue by RayTNT1531** [lo-cafe/winston#498] opened 2024-05-01 04:39 UTC
Pretty self-explanatory, not having an option to download videos and GIFs inside the app is the only grievance I have with Winston, and adding this feature would make this app probably the best Apollo replacement.

**Comment by ojsef39** [comment] 2024-05-01 09:36
duplicate of #178

**Closed** 2024-05-01 09:37 UTC
Labels: feature/enhancement
